### ISSUE TITLE
Create branches, project and wikis

### ISSUE THREAD

**Issue by vikrantdeshpande09876** [airavata-courses/scapsulators#12]
Set up initial Github environment for proper release-management.

**Comment by vikrantdeshpande09876** [comment]
Branches and Project setup completed.
Wikis' creation is next up.

**Comment by vikrantdeshpande09876** [comment]
@RutujaJadhav19 , @shubhpatr - Could you guys take over the remaining Wikis-creation? Need to add Use-case diagram, Napkin diagram, and small user-lifecycle diagram (login->homepage->view/analyze->capture audits->logout).

**Comment by shubhpatr** [comment]
Reviewed and looks okay!
