### ISSUE TITLE
Create Flow Diagram for user-lifecycle

### ISSUE THREAD

**Issue by vikrantdeshpande09876** [airavata-courses/scapsulators#41]
Wikis do not yet clearly convey how state changes will be made for user lifecycle.

A clear and concise diagram of what needs to happen:

login -> homepage -> make request -> view weather-report -> view audit logs

**Comment by RutujaJadhav19** [comment]
@vikrantdeshpande09876 , @shubhpatr 
Can we use the project flow diagram from this sheet - https://github.com/airavata-courses/scapsulators/blob/main/Documentation/Microservices-Overview/Project%201-%20ADS%20-%20Design%20Proposal%201.xlsx
