### ISSUE TITLE
Merge changes into release-branch

### ISSUE THREAD

**Issue by vikrantdeshpande09876** [airavata-courses/scapsulators#49]
Need a central branch with single-point of entry for entire system.

**Comment by vikrantdeshpande09876** [comment]
First round of manual integration-tests successful in [development-project1-release](https://github.com/airavata-courses/scapsulators/tree/development-project1-release).
Next steps: Replicate behaviour into [project1-release](https://github.com/airavata-courses/scapsulators/tree/project1-release).

**Comment by RutujaJadhav19** [comment]
It looks good to me.

**Comment by vikrantdeshpande09876** [comment]
Done!
