### ISSUE TITLE
Bugs Found during Integration testing of project 1 Release.

### ISSUE THREAD

**Issue by RutujaJadhav19** [airavata-courses/scapsulators#53]

**Comment by RutujaJadhav19** [comment]
These are bugs encountered during integration testing of project 1.
1) The FE pops up a window saying Query failed when there is no data for that particular date, It should say there is no data available for that selection of parameters.
2) On the home page, there is a back-to-home page link which is not necessary.
3) During sign up, the user has to sign the terms and conditions which redirects to google and not the terms and conditions page. 
4) When we reset the password, if the security answer is incorrect, it says username does not exist when it should say the answer is incorrect.
5) For Reset password, the placeholder says enter your email address and we will send you the password when that is not our functionality.

**Comment by shubhpatr** [comment]
Made all the written changes. Closing this now
