### ISSUE TITLE
Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use

### ISSUE THREAD

**Issue by reinforcedByRL** [airavata-courses/scapsulators#72]
Getting this error after I ran the start-up script. 
ERROR: for library-api  Cannot start service library-api: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use
ERROR: Encountered errors while bringing up the project.
![Screen Shot 2022-02-22 at 1 59 28 AM](https://user-images.githubusercontent.com/11539935/155079203-11229190-d8f7-4772-8159-ce4b2a6480c9.png)

**Comment by vikrantdeshpande09876** [comment]
Hi Sreesha
1. The same issue was highlighted in #63 where an Apple MacBook runs the Air Play application by default on port 5000, and we should have some script to check for ports-currently-in-use. 
We're triaging this for our next release.
For now could you try disabling/killing the process for Air Play?

2. Additionally, another issue we've noticed and highlighted in the documentation is- there's a compatibility issue of the Python 
microservice dependency on a Mac M1 system. This leads to intermittent responses as noted in #62.
We've got a workaround planned for the underlying Docker image, in the next release.

**Comment by vikrantdeshpande09876** [comment]
@shubhpatr - Let's track this change of gateway port-number in this release-2 itself.

**Comment by vikrantdeshpande09876** [comment]
Fixed! 🥳 💯 
Will be in Production-release branch on 4th March.
