### ISSUE TITLE
weather-reporter      | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3> weather-reporter exited with code 1

### ISSUE THREAD

**Issue by reinforcedByRL** [airavata-courses/scapsulators#74]
weather-reporter      | Traceback (most recent call last):
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
weather-reporter      |     self.sleep()
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
weather-reporter      |     ready = select.select([self.PIPE[0]], [], [], 1.0)
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
weather-reporter      |     self.reap_workers()
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
weather-reporter      |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
weather-reporter      | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
weather-reporter      |
weather-reporter      | During handling of the above exception, another exception occurred:
weather-reporter      |
weather-reporter      | Traceback (most recent call last):
weather-reporter      |   File "/opt/conda/envs/env/bin/gunicorn", line 8, in <module>
weather-reporter      |     sys.exit(run())
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
weather-reporter      |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
weather-reporter      |     super().run()
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
weather-reporter      |     Arbiter(self).run()
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
weather-reporter      |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
weather-reporter      |     self.stop()
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
weather-reporter      |     time.sleep(0.1)
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
weather-reporter      |     self.reap_workers()
weather-reporter      |   File "/opt/conda/envs/env/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
weather-reporter      |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
weather-reporter      | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
weather-reporter exited with code 1

**Comment by vikrantdeshpande09876** [comment]
Likely linked to #62 , gunicorn is probably shutting down because application instance can't be created on worked nodes.
Marking this as duplicate.
